# cloudformation-template.yml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'FunLand Kids Park Application Stack'

Parameters:
  EnvironmentName:
    Description: 'Application Environment'
    Type: String
    Default: 'production'
    AllowedValues:
      - staging
      - production

Resources:
  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: "FunLand Kids Park Application"
      
  ApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref Application
      Description: Version 1.0
      SourceBundle:
        S3Bucket: !Sub "funland-artifacts-${AWS::AccountId}"
        S3Key: !Sub "funland-app-${EnvironmentName}.zip"
        
  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref Application
      EnvironmentName: !Sub "funland-${EnvironmentName}"
      SolutionStackName: "64bit Amazon Linux 2 v3.4.11 running Docker"
      VersionLabel: !Ref ApplicationVersion
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:elasticbeanstalk:healthreporting:system
          OptionName: SystemType
          Value: enhanced